### ISSUE TITLE
signatureType in QRLDescriptor is not zero but 1

### ISSUE THREAD

**Issue by ElleryHao** [theQRL/go-qrllib#31]
FYI

so the address i got starts by 'Q110500' , and blockchain explorer seems not support this

**Comment by jplomas** [comment]
Hi.

github.com/theQRL/qrllib contains the necessary code for existing QRL mainnet integration in Golang.

This is a work-in-progress library for the upcoming Zond node. It is anticipated to change and break any dependencies, so caution is advised.

We've reverted the XMSS descriptor index in this library, which should help legacy address creation using this library if this is helpful for what you need.

Please don't hesitate to reach out if you have a particular use case in mind, and we can try and point you in the right direction.
